CC = gcc
LIB = -lsocket -lnsl -m64 -lpthread -std=c99

all: client server

server: myftpserver.c
	${CC} -o myftpserver myftpserver.c ${LIB}

client: myftpclient.c
	${CC} -o myftpclient myftpclient.c ${LIB}

clean:
	rm myftpclient
	rm myftpserver
