CC = gcc
LIB = -lpthread -std=c99

all: client server

client: myftpclient.c
	${CC} -o myftpclient myftpclient.c ${LIB}

server: myftpserver.c
	${CC} -o myftpserver myftpserver.c ${LIB}

clean:
	rm myftpclient
	rm myftpserver
		
